### ISSUE TITLE
Istallation error

### ISSUE THREAD

**Issue by hamelena** [Koziev/rusyllab#1]
Hi!
While installing I get the error message:

`ERROR: Command errored out with exit status 1:
     command: 'c:\python\python38-32\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\JLU-SU\\AppData\\Local\\Temp\\pip-req-build-w1soouyd\\setup.py'"'"'; __file__='"'"'C:\\Users\\JLU-SU\\AppData\\Local\\Temp\\pip-req-build-w1soouyd\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base pip-egg-info
         cwd: C:\Users\JLU-SU\AppData\Local\Temp\pip-req-build-w1soouyd\
    Complete output (7 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\JLU-SU\AppData\Local\Temp\pip-req-build-w1soouyd\setup.py", line 4, in <module>
        long_description = fh.read()
      File "c:\python\python38-32\lib\encodings\cp1252.py", line 23, in decode
        return codecs.charmap_decode(input,self.errors,decoding_table)[0]
    UnicodeDecodeError: 'charmap' codec can't decode byte 0x8f in position 582: character maps to <undefined>`

Do you understand what the problem is? Other packages are properly installed.
Thank you in advance.

**Comment by Koziev** [comment]
Hi!

The reason is about cp1252 encoding and Windows console I suppose.
Please pull changes from this repo and try to install again.

**Comment by hamelena** [comment]
Hi! Now it is working, perfect! Thank you so much.
